// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm7Oc0iZOlXK3VbAM_ExEu7gZae-fWKaM',
    appId: '1:437175363680:web:cf1742091a5aa556e5bb05',
    messagingSenderId: '437175363680',
    projectId: 'deardiary-9f3b0',
    authDomain: 'deardiary-9f3b0.firebaseapp.com',
    storageBucket: 'deardiary-9f3b0.appspot.com',
    measurementId: 'G-5DLBKWVKZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhqdrgvNA6NyGTAoWHgpULvWNTWKUJo2g',
    appId: '1:437175363680:android:e3b62b44ddee5face5bb05',
    messagingSenderId: '437175363680',
    projectId: 'deardiary-9f3b0',
    storageBucket: 'deardiary-9f3b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj2kkw9533dj2TrrKlkbIexxIRwAGTsO4',
    appId: '1:437175363680:ios:fb54ad084274c5eae5bb05',
    messagingSenderId: '437175363680',
    projectId: 'deardiary-9f3b0',
    storageBucket: 'deardiary-9f3b0.appspot.com',
    iosClientId: '437175363680-9m20r0h2g63l07huce7a9q688g65mp38.apps.googleusercontent.com',
    iosBundleId: 'com.example.deardiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj2kkw9533dj2TrrKlkbIexxIRwAGTsO4',
    appId: '1:437175363680:ios:57cd713054915aa3e5bb05',
    messagingSenderId: '437175363680',
    projectId: 'deardiary-9f3b0',
    storageBucket: 'deardiary-9f3b0.appspot.com',
    iosClientId: '437175363680-d8agj146mj789ignhgvcs8fejktgo2bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.deardiary.RunnerTests',
  );
}
